import {
  NavbarContainerDiv,
  NavbarIconDiv,
  NavbarContentDiv,
  NavbarChildDivs,
  Navbartext,
} from "./Navbar/Navbar.styles";

import {
  BandImageDiv,
  BandHeading,
  BandSubheading,
  BandDatapara,
  BandImageTag,
  BandNameTag,
  BrandImageTagChildDiv,
  BandcontainerDiv,
} from "./Band/Band.styles";

import { StyledCarouselImage } from "./Carousel/Carousel.styles";

import {
  TourContainerChildDiv,
  TourHeadingDiv,
  TourHeading,
  TourSubHeading,
  TourContainerDiv,
  TicketStatusDiv,
  TicketStatusChildDiv,
  TourSeptember,
  TourSoldOut,
  TourNumberDiv,
  TourTextTag,
  TourCardMainDiv,
  TourCardChildDiv,
  TourCardChildImage,
  TourCardHeadTag,
  TourCardDateTag,
  TourCardDetailsDiv,
  TourCardButton,
  TourCardButtonText,
} from "./Tour/Tour.styles";

import {
  ContactHeading,
  ContactSubHeading,
  ContactMainContainer,
  ContactTopDetailsContainer,
  ContactTopInsideDetailsDiv,
  ContactDeepInside,
  Contactinput,
  SecondContactInput,
  ContactButton,
  ContactButtonText,
  ContactImageTag,
  LastTextTag,
} from "./Contact/Contact.styles";

export {
  Navbartext,
  NavbarChildDivs,
  NavbarContainerDiv,
  NavbarIconDiv,
  NavbarContentDiv,
  StyledCarouselImage,
  BandcontainerDiv,
  BandHeading,
  BandSubheading,
  BandDatapara,
  BandImageDiv,
  BandImageTag,
  BandNameTag,
  BrandImageTagChildDiv,
  TourHeading,
  TourSubHeading,
  TourContainerDiv,
  TourHeadingDiv,
  TourContainerChildDiv,
  TicketStatusDiv,
  TicketStatusChildDiv,
  TourSeptember,
  TourSoldOut,
  TourNumberDiv,
  TourTextTag,
  TourCardMainDiv,
  TourCardChildDiv,
  TourCardChildImage,
  TourCardHeadTag,
  TourCardDateTag,
  TourCardDetailsDiv,
  TourCardButton,
  TourCardButtonText,
  ContactHeading,
  ContactSubHeading,
  ContactMainContainer,
  ContactTopDetailsContainer,
  ContactTopInsideDetailsDiv,
  ContactDeepInside,
  Contactinput,
  SecondContactInput,
  ContactButton,
  ContactButtonText,
  ContactImageTag,
  LastTextTag,
};
